### ISSUE TITLE
Impossible to follow development

### ISSUE THREAD

**Issue by enoch85** [ezraholm50/BerryCloud#15]
Hey Ezra, 

It's almost impossible to follow the development with all those small commits. Don't you use git anymore?

**Comment by ezraholm50** [comment]
Hey daniel did not have my laptop on me last few days thats why I also am
not on irc. Will clean it soon so its fresh again.

Op wo 4 mei 2016 19:30 schreef Daniel Hansson <notifications@github.com>:

> Hey Ezra,
>
> It's almost impossible to follow the development with all those small
> commits. Don't you use git anymore?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/15>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by enoch85** [comment]
@ezraholm50 Naah, no need to clean, it was just a thought. Hope you are doing fine! Was a long time since we talked. :)

**Comment by ezraholm50** [comment]
Ill be on irc soon mate, busy days... would love to catch up on everything.

Op wo 4 mei 2016 19:54 schreef Daniel Hansson <notifications@github.com>:

> Closed #15 <https://github.com/ezraholm50/BerryCloud/issues/15>.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/15#event-650553612>
>
-- 

Met vriendelijke groet,

E. Holm
