### ISSUE TITLE
Working for a month and now nothing..

### ISSUE THREAD

**Issue by utp216** [ezraholm50/BerryCloud#16]
Please take a look at this and tell me if this is something I can fix. I don't know what happened really. The server was working fine and then one day I couldn't connect. I logged in via ssh and this is what I see.

Thanks!
![berrycloud_readonly](https://cloud.githubusercontent.com/assets/6845886/15135466/6a427168-1644-11e6-9bdb-8107fada975e.PNG)

**Comment by ezraholm50** [comment]
Quick fix is to do: sudo mount -o remount,rw /partition/identifier /

/partition/identifier should be changed to /dev/sda1 for HD and
/dev/mmcblk0p2 for sdcard

Then you could add that same line in /etc/rc.local like this after you have
run the command: sudo echo"mount -o remount,rw /partition/identifier /" >>
/etc/rc.local

I will look into this problem soon.

Also run: apt-get update && apt-get upgrade -y

Op di 10 mei 2016 06:16 schreef utp216 <notifications@github.com>:

> Please take a look at this and tell me if this is something I can fix. I
> don't know what happened really. The server was working fine and then one
> day I couldn't connect. I logged in via ssh and this is what I see.
>
> Thanks!
> [image: berrycloud_readonly]
> <https://cloud.githubusercontent.com/assets/6845886/15135466/6a427168-1644-11e6-9bdb-8107fada975e.PNG>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/16>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by utp216** [comment]
Those commands didn't seem to work/do anything.

I was able to do 'e2fsck -f /dev/sda2' and now I think everything is working again.

**Comment by ezraholm50** [comment]
Weird, you could add that line to /etc/rc.local as a precaution... please
keep me updated if it happens again. Also what is you bootdelay/rootdelay
in /boot/cmdline.txt.

And are you using a harddisk or sdcard only?

Op wo 11 mei 2016 04:44 schreef utp216 <notifications@github.com>:

> Those commands didn't seem to work/do anything.
>
> I was able to do 'e2fsck -f /dev/sda2' and now I think everything is
> working again.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/16#issuecomment-218347830>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by ezraholm50** [comment]
Also did you change the source to the right device?

**Comment by utp216** [comment]
This is the contents of cmdline.txt -

smsc95xx.macaddr=b8:27:eb:08:8f:7c smsc95xx.turbo_mode=N dwc_otg.fiq_fix_enable=1 root=/dev/sda2 rootfstype=ext4 wc_otg.lpm_enable=0 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait rootdelay bootdelay

I am booting from SD card and have 1TB PiDrive attached to RPi3.

I am going to test again but I don't think owncloud is working properly. I can ssh to the Pi without error and log in to webmin, etc. 

I can't seem to log in with the owncloud client in Windows.

**Comment by utp216** [comment]
This is the strange behavior I have after getting the hard drive writable again.

If I use the Windows client and select the server address as https://10.0.0.200/owncloud I see this error and that is as far as it goes. 
![owncloud_error_1](https://cloud.githubusercontent.com/assets/6845886/15181852/6b0fa7dc-1757-11e6-807a-87a733668041.PNG)

If I use the Windows client and select the server address as https://10.0.0.200/ I see this -

![owncloud_no_files](https://cloud.githubusercontent.com/assets/6845886/15181870/817d94f2-1757-11e6-914c-62fde18d04fd.PNG)

It allows me to log in but has no files/folders. 

I can't log in at all with web browser. I enter the name and password and the screen just refreshes and blanks out the name.

**Comment by ezraholm50** [comment]
I'll be on this tonight

Op wo 11 mei 2016 15:06 schreef utp216 <notifications@github.com>:

> This is the strange behavior I have after getting the hard drive writable
> again.
>
> If I use the Windows client and select the server address as
> https://10.0.0.200/owncloud I see this error and that is as far as it
> goes.
> [image: owncloud_error_1]
> <https://cloud.githubusercontent.com/assets/6845886/15181852/6b0fa7dc-1757-11e6-807a-87a733668041.PNG>
>
> If I use the Windows client and select the server address as
> https://10.0.0.200/ I see this -
>
> [image: owncloud_no_files]
> <https://cloud.githubusercontent.com/assets/6845886/15181870/817d94f2-1757-11e6-914c-62fde18d04fd.PNG>
>
> It allows me to log in but has no files/folders.
>
> I can't log in at all with web browser. I enter the name and password and
> the screen just refreshes and blanks out the name.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/16#issuecomment-218453209>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by ezraholm50** [comment]
What ownCloud version do you have, I assume 9.01? If so please run this script: https://gist.github.com/ezraholm50/69cb27b1c444f48dbb9b2bd09ca61eab

And report back to me.

**Comment by utp216** [comment]
Script is processing now. I can see the files I had synced scrolling by.. (FINGERS CROSSED!)

**Comment by ezraholm50** [comment]
Any progress?

**Comment by utp216** [comment]
Unfortunately I had to leave for work and can't access home from here. I will report back tonight when I return home.

**Comment by ezraholm50** [comment]
No problem, I won't be on much longer. I will reply to your post first thing in the morning!

**Comment by utp216** [comment]
Everything is working again! 

I retried a sync and my desktop and the server are matching perfectly!

Thank you for your help!

**Comment by ezraholm50** [comment]
Good to hear, although I can't say exactly what it was... I think it where 2 things.

I will post my findings for other users...

The login loop had to do with a PHP7.0 upgrade and a core issue. Upgrading to 9.0.2 fixed it. This script can be used https://gist.github.com/ezraholm50/69cb27b1c444f48dbb9b2bd09ca61eab

The read only is a unknown to me. It could be solved with the upgrade from 15.10 to 16.04

Please look at the [Ubuntu upgrade wiki page](https://github.com/ezraholm50/BerryCloud/wiki/a-Update-Ubuntu-15.10-to-16.04) to upgrade your distro.

@utp216 Please also run: `apt-get update && apt-get upgrade -y`
