### ISSUE TITLE
Where have this code moved? 

### ISSUE THREAD

**Issue by enoch85** [ezraholm50/BerryCloud#18]
The link in the description is wrong

**Comment by ezraholm50** [comment]
fixed https://github.com/ezraholm50/NextBerry

**Comment by enoch85** [comment]
Please update on Tech and Me as well, thanks! :)

**Comment by ezraholm50** [comment]
First it needs to be stable! As soon as thats the thing I'll update it.

**Comment by enoch85** [comment]
Ok cool
