### ISSUE TITLE
Address to latest ownCloud RC

### ISSUE THREAD

**Issue by enoch85** [ezraholm50/BerryCloud#29]
https://download.owncloud.org/community/testing/owncloud-9.0.0RC3.tar.bz2

So OCVERSION would in this case be "9.0.0RC3".

```
OCVERSION=9.0.0RC3
DIR=whatever
wget -q https://download.owncloud.org/community/testing/owncloud-$OCVERSION.tar.bz2 -P $DIR
```
cc @ezraholm50

**Comment by ezraholm50** [comment]
Works great mate thanks, seen what I did wrong on mobile today, just a typo... thanks!
Will file some changes to the script tonight!

**Comment by enoch85** [comment]
:+1:
