### ISSUE TITLE
output of : sudo ifdown -a && ifup -a && sudo cat /etc/network/interfaces

### ISSUE THREAD

**Issue by utp216** [ezraholm50/BerryCloud#4]
I tried the command that you listed and this is what is outputted -

sudo: unable to resolve host localhost.localdomain
ifup: failed to open lockfile /run/network/ifstate.lo: Permission denied

I went ahead and changed root password with 'sudo passwd root' and then 'su''d on command line. The output changed to this -

I will post picture of screen, I have no way of grabbing output and posting text.

**Comment by utp216** [comment]
Sorry for having to post screenshots like this.

http://imgur.com/4jghF4x

**Comment by ezraholm50** [comment]
Thats no problem I get it.

Ok I see my cmd is wrong.

`sudo ifdown -a && sudo ifup -a && ifconfig`

See if eth0 is listed.

Also try apt-get update, if it fails to connect, please check the hardware, router MAC control, cable fault. Just tested it at home, everything works.

**Comment by enoch85** [comment]
@utp216 Try this command and post the output here, `ip -o link show | awk '{print $2,$9}' | grep "UP" | cut -d ":" -f 1`

Thanks!

**Comment by ezraholm50** [comment]
type: sudo nano /etc/network/interfaces

Example before (look at auto eth0):

```
auto lo
iface lo inet loopback

The primary network interface
auto eth0
iface eth0 inet dhcp
```

Example after (look at allow-hotplug eth0):
```
auto lo
iface lo inet loopback

The primary network interface
allow-hotplug eth0
iface eth0 inet dhcp
```

Please tell me the outcome.

**Comment by ezraholm50** [comment]
Ignore the above post, run this instead:

`sudo rm /etc/udev/rules.d/70-network-devices.rules && reboot`

That should work, since it contained the MAC address of my testing PI.

**Comment by ezraholm50** [comment]
Add this line to cmdline.txt to the end of the first line. Found in /boot or PI_BOOT partition or download a fresh image.

`smsc95xx.macaddr=b8:27:eb:08:8f:7c`

**Comment by utp216** [comment]
Sorry for delay, I just returned home from work.

I've tried everything but can't seem to find cmdline.txt in /boot/

Should I create the file and add the mac address line?

**Comment by utp216** [comment]
I am downloading the fresh image and starting from there. Going to see what happens! I can't wait to get this setup and have my PiDrive working with the extra storage space!

**Comment by utp216** [comment]
This is totally working so far! Install is downloading the scripts from Github right now!

**Comment by ezraholm50** [comment]
Great to hear, took me a while to figure out. How is it going so far, have it up and running yet?

**Comment by utp216** [comment]
Lets just say this!

http://imgur.com/DeaBQIk

Thank you and the rest of the developers for the work you are doing! I am testing everything now!
