### ISSUE TITLE
Letsencrypt

### ISSUE THREAD

**Issue by ezraholm50** [ezraholm50/BerryCloud#6]
Seems to work with a valid cert, certs where not found within the mentioned dir in apache vhost.
Certs worked on the domain though. Terminal installation retried 4 times without any luck, breaks the install at reverting, apache vhost 443 gets deleted.

Also it seemed that port 443 needs to be open in order to work.

**Comment by enoch85** [comment]
Explain a bit more please, was ages since I wrote that script. Would be nice if you could debug it.

**Comment by ezraholm50** [comment]
Well, everything went well, during the script right before it gave the message: try 1 failed, trying a second time, i could visit my domain and have a green lock, thus it worked.

Then it gave some errors on all 4 tries after that. Then the 'failsafe' if we want to call it that, deleted the virtual host 443, so the system broke down.

**Comment by enoch85** [comment]
Hmm... So in other words, it succeeded and then it didn't recognize the files and therefore continued to try? So the path where the scripts are saved is wrong? 

Then the question is, where are they saved?

**Comment by enoch85** [comment]
Right now it's:
```
letsencryptpath=/etc/letsencrypt
certfiles=$letsencryptpath/live
```

**Comment by ezraholm50** [comment]
Yeah indeed. but during that script (in between the 4 tries) i went to that directory but the live doesn't exists.

**Comment by enoch85** [comment]
Can you debug it? It's a simple change of path, that's all. I need to know where the scripts are saved.

**Comment by ezraholm50** [comment]
Works!
