### ISSUE TITLE
HTML path wrong in owncloud_update.sh / download fails with 404

### ISSUE THREAD

**Issue by cprinze** [ezraholm50/BerryCloud#8]
please change to /var/www without html
also the download fails with 404

**Comment by ezraholm50** [comment]
What download the one owncloud_update.sh initiates?

**Comment by cprinze** [comment]
yes

**Comment by ezraholm50** [comment]
The owncloud-9.0.0.tar.bz2?
That one has become stable, I changed it. Note that the script is only if you want to use a higher version then you currently have, you have to specify it in the var VERSION. You could also just use owncloud updater in the admin panel.

This script however backups everything properly before updating.

**Comment by cprinze** [comment]
i know, was simply meant to get clean :)

**Comment by ezraholm50** [comment]
Thanks, you can PR next time if you're sure the fix works! Appreciate the help!
